export const Titles = [
	"#EXPOSETHECOWARDS",
	"#viperrevolution",
	"1 Million Vipers but Only 1 Vipa",
	"1 Million Vipers but Only 1 Viper",
	"1,000,000 Vipers but Only 1 Vipa",
	"18 Wheela",
	"2 4 U",
	"2 Burn a Cop Alive",
	"2 Burn a Police Alive",
	"2 Decapitate a Cop",
	"2 Hot",
	"4eva Tha Realest",
	"A Day in the Life of Lee Carter",
	"A Day in the Life of Lee Carter",
	"A Greater Man Than U",
	"A Greater Man",
	"A Hustler's Life",
	"A Hustler's Life",
	"A Hustler's Life",
	"A Hustler's Life",
	"A Loose Cannon",
	"A Loyal Illuminati Memba II",
	"A Loyal Illuminati Memba",
	"A Sweet Eulogy",
	"A Young Hustler's Life (Baller's Mix)",
	"Ability II",
	"Ability",
	"Above All Law",
	"Above All Laws",
	"Addiction",
	"Ahead of All Tyme",
	"Ahead of His Tyme",
	"Ahead of U All Tha Tyme",
	"Ahead of Ur Tyme",
	"All 4 U Fam",
	"All Dis Money Dirty",
	"All Dogs Go to Heaven",
	"All Play No Work",
	"All Play, No Work",
	"All the Bad B*tches Choosin' Me",
	"Alot of Folk Countin' on Me",
	"Always Feelin Good",
	"An Unmatched Resolve",
	"Annihilation",
	"Aquatic Hoes",
	"Are U Really That Stupid",
	"Ass Floss",
	"At Peace Wit My Peace",
	"Atomic Bombs and Mutually Assured Destruction Is Fuckin' Stupid II",
	"Attackin' Tha Rim Daily",
	"Attackin' Tha Rim",
	"Bad Apple II",
	"Bad B*tches All On Me",
	"Bad B*tches Non-Stop Choosin' Me",
	"Bad B*tches Stayin' on Me",
	"Banned from Tha Rap Game",
	"Beach Hottie U Want",
	"Bearin' Interest",
	"Big Girls 4 U",
	"Bikini so Lovely",
	"Blessed by My Patience",
	"Blonde in Ur Bed",
	"Blood in, Blood Out",
	"Body Is a Temple",
	"Boo 4 U",
	"Booty 4 Days",
	"Boys Talkin' Down",
	"Break Bread Bro",
	"Break Bread",
	"Breakin' Tha Ice II",
	"Breakin' That Ice",
	"Business Cash",
	"Business Money",
	"Calculated Presence",
	"Cash Graze",
	"Celebrate!",
	"Celebrate",
	"Celebration",
	"Chin Checka",
	"Chopped And Screwed-Hustlin' Thick",
	"Cloned & Copied",
	"Cloned & Copied",
	"Cloned While Copied",
	"Cloudy Grinna",
	"Cocaine Snorta",
	"Code of Tha Streets II",
	"Code of Tha Streets",
	"Code of These Streets II",
	"Combo Breaker",
	"Concrete Jungle",
	"Concrete Jungle",
	"Concrete Jungle",
	"Concrete Jungle",
	"Concrete Jungle",
	"Concrete Jungle",
	"Confidence",
	"Confident II",
	"Cop Killa",
	"Cop Murdera",
	"Copied & Cloned",
	"Cops Can't Read III",
	"Cops Can't Read",
	"Crack Deala",
	"Crack Sella",
	"Creata of Hardcore Rap",
	"Creata of Rapcore",
	"Crime Scene",
	"Crime Scenes II",
	"Crunk",
	"Cum Here Now!!",
	"Damn I Want U Bad",
	"Dead Man Walkin'",
	"Deadly Weapon II",
	"Deala of Dope 2",
	"Deala of Dope",
	"Death Awaits",
	"Death Before Dishonor",
	"Death of a Salesman",
	"Deep in Tha Hustle",
	"Deep in That Hustle",
	"Defiance",
	"Defiant",
	"Dimples and Muscles",
	"Dimples",
	"Dis 4 Real",
	"Dis Deadly Weapon II",
	"Dis Deadly Weapon",
	"Dis Fight 4 Control II",
	"Dis Fight 4 Control",
	"Dis Liquid Fury II",
	"Dis Liquid Fury",
	"Dis Nigga Here!",
	"Dis What It Be 'Bout II",
	"Dis What It's All Bout",
	"Dis Winna Life!",
	"Do It in Tha Pool",
	"Don't Fuq Wit Her Clique",
	"Don't Knock a Hustle",
	"Don't Knock My Hustle!",
	"Don't Knock My Hustle",
	"Don't Talk Down",
	"Dope Deala",
	"Dream Steppin",
	"Dream Steppin",
	"Dreams In The Penitentary",
	"Dreams of a Rap Star",
	"Educatin' Tha Community",
	"Education 4 Tha Community",
	"End Ur Life Dummy",
	"End Ur Life Stupid",
	"Engineered 2 Amaze II",
	"Engineered 2 Amaze U",
	"Eternal Parlayin'",
	"Eternal Parlayin'",
	"Eternal Playboy",
	"Eternal Prettyboy",
	"Euthanasia",
	"Euthanization",
	"Every Dog Has His Day",
	"Everyday a Vacation",
	"Evil 1 II",
	"Evil 1",
	"Evrythang I Live 4",
	"F!ck U Pussy-Ass N!gga",
	"F!Ck U Pussy",
	"F!Ck U",
	"F#ck U Bastards",
	"F#ck U Pussies",
	'F$Ck 24" And Up',
	"F$ck All 24 and Up",
	"F%ck a Wedding",
	"F%ck the Police!",
	"F%ck the Pussy Police!",
	"F%ck U Pussy-Ass N%gga II",
	"F%Ck U Pussy-Ass N%Gga III",
	"F%ck U Pussy-Ass N%gga",
	"F%ck Ur Label Pussy",
	"F%ck Ur Record Label Pussy",
	"F%ck Ur Wedding",
	"F*ck the Pussy Police",
	"F*ck U",
	"F*ck What U Heard",
	"F*ck What U Sayin'",
	"F@ck the Police",
	"F@ck What U Believe In",
	"F@ck What U Goin' Through",
	"F@ck What U Stand 4",
	"Find Me on Tha Beaten Path",
	"Fish And Chips",
	"Fish And Chips",
	"Fish And Chips",
	"Fish and Chips",
	"Folk Countin' on Me",
	"Forestry Maj-A Imma Keep Ur Lil Bears Safe",
	"Fuck Tha World It Ain't Real I Bend Tha Spoon Wit My Mind 2",
	"Fuck U Cops!!! II",
	"Fuck U Cops!!!",
	"Fuck U Little Nigger",
	"Fuck U Pussy-Ass Nigga",
	"Genius",
	"Get Loose Wit It",
	"Give It 2 Her",
	"Gleam",
	"Gleam",
	"Gleam",
	"Gleam",
	"Gleam",
	"God Bless Rap F!Ck Hip Hop",
	"God Bless Rap F$ck Hip Hop",
	"God Bless Rap F%ck Hip Hop",
	"God Bless Rap F@ck Hip Hop",
	"God Has No Luv 4 U",
	"God Has No Respect 4 U",
	"God Hates U and Luvs Me",
	"God Hates U and Luvs Me",
	"God of Hardcore Rap",
	"God of Rapcore",
	"God's Favorite Human Being",
	"God's Favorite Human",
	"God's Greatest Creation",
	"God",
	'Google "Rapper Viper"',
	"Google Rapper Viper Now",
	"Gorgeous Boy",
	"Gorgeous",
	"Got Tha Models Wide Open",
	"Gots 2 Make It Work",
	"Gots a Wicked Pistol Game",
	"Gots That Top Street Cred",
	"Grind Climb",
	"Grind To Shine",
	"Grind To Shine",
	"Grind To Shine",
	"H-Town's Top Choice",
	"Half Ur 6 Pac Higha Than Tha Otha Half",
	"Hard Work",
	"Haterproof",
	"Haters Talkin' Down",
	"Heartless Hoodlum (Viper-15 songs)",
	"Heartless Hoodlum Futuristic Space Age Remix Album (RymeTymerecords.com",
	"Heartless Hoodlum Futuristic Space Age Remix Album / Screwed and Chopped",
	"Heartless Hoodlum",
	"Heartless Hoodlum",
	"Heartless Hoodlum",
	"Heartless Hoodlum",
	"Heartless Hoodlum",
	"Heartless Hoodlum",
	"Heartless Hoodlum",
	"Heartless Hoodlum",
	"Heaven Is fo' Reel Muthafucka 3",
	"Hi Potency",
	"Hiram Clark Hustler",
	"Hiram Clarke Hustler",
	"Hoes Want to See U",
	"Hold Her Hand",
	"Hold U Down 4 Life",
	"Hole in Tha Sky Is Mad Real II",
	"Holy Mutha A' God II",
	"Holy Mutha A' God",
	"Hot Thang 4 U",
	"How Can I Help U?",
	"How I Make U Feel",
	"How It Makes U Feel II",
	"Human Cryonics: My Burial Site",
	"Human Cryostasis Gangsters Don't Die",
	"Hustlin Thick, Lovin Big",
	"Hustlin' Thick Chopped and Screwed",
	"Hustlin' Thick II",
	"Hustlin' Thick",
	"I Ain't Playin 3",
	"I Ain't Playin",
	"I Am a Lot Smarter Than U",
	"I Am Betta Than U",
	"I Am God",
	"I Am Superior 2 U",
	"I Am Superior",
	"I Am Superior",
	"I Be Real as Gold 4 Sho II",
	"I Found Ot I'm That Nigga",
	"I Got Tha Cure 4 a Broken Heart Right Here",
	"I Got Ya",
	"I Have Tha Best Piece & Chain Eva Made!",
	"I Have the Best Piece and Chain Ever Made",
	"I Know U Want It",
	"I Mastaed Life",
	"I No What U Been Missin'",
	"I Remember All My Dreams II",
	"I Remember All My Dreams",
	"I Seen a Skull",
	"I Sell Tha Best Crack 2",
	"I Sell Tha Best Crack",
	"I Win Always, U Loose Always",
	"I'm 5-9 Piru Blood (Now You Know My Set)",
	"I'm a 5-9 Piru Blood",
	"I'm a 5-9 Piru Blood",
	"I'm a Greater 1 Than U II",
	"I'm a Greater 1 Than U",
	"I'm a Greater 1",
	"I'm Alot Smarter Than U",
	"I'm Better Than U II",
	"I'm Better Than U",
	"I'm Gonna Kill Them Pussy Niggas That Killed 2pac",
	"I'm Gonna Kill Them Pussy Niggas That Killed 2Pac",
	"I'm Gonna Smoke Them Pussy Niggas That Killed 2pac II",
	"I'm Gonna Smoke Them Pussy Niggas That Killed 2pac",
	"I'm Gonna Smoke Them Pussy Niggas That Killed 2Pac",
	"I'm Greater Than U",
	"I'm Incredible",
	"I'm Lovin' Here Dis Rap Game Money",
	"I'm Luvin' Dis Here Rap Game II",
	"I'm Luvin' Dis Here Rap Game III",
	"I'm Luvin' Dis Here Rap Game...",
	"I'm Luvin' Dis Here Rap Game",
	"I'm Luvin' Dis Here Rap Money Cause It's Different II",
	"I'm Luvin' Dis Here Rap Money Cause It's Different",
	"I'm Luvin' Dis Rap Game Money II",
	"I'm Luvin' Dis Rap Game Money III",
	"I'm Luvin' Dis Rap Game Money",
	"I'm Luvin' Dis Rap Game",
	"I'm Luvin' Dis Rap Money Cause It's Different Than Regular Money",
	"I'm Luvin' Dis Rap Money Cause It's Different",
	"I'm Luvin' Tha Rap Money Cause It's Different",
	"I'm Much Smarter Than U",
	"I'm so Incredible",
	"I'm So Much Smarter Than U",
	"I'm so Much Smarter Than U",
	"Ice Cold",
	"Im Better Than U",
	"Im Talkin' 'Bout Makin' the Bed Rock Like a Flintstone",
	"Impeccable II",
	"Impeccable",
	"In A Thug's Life",
	"In A Thug's Life",
	"In A Thug's Life",
	"In A Thug's Life",
	"In A Thug's Life",
	"In My Gat I Trust",
	"In Tha Life of a Rap Star",
	"Incomparable!",
	"Incomparable",
	"Interest Bearin'",
	"Inventa of Hardcore Rap",
	"It Don't Get No Betta",
	"It Would Be Heaven on Earth If Cops Were Drafted & Not Hired",
	"It'd Be Heaven On Earth If Cops Were Drafted & Not Hired",
	"It'd Be Heaven on Earth If Cops Were Drafted and Not Hired",
	"It's 4 Real",
	"It's All Because of Me ;-(",
	"It's All Because of U ;-(",
	"It's Because of Me",
	"It's Because of U ;-(",
	"It's Not Worth Yo Life",
	"It's Ok, U Can Judge Me",
	"It's Real",
	"Jagua Man 2",
	"Judged By 12, Saluted By a Million",
	"Just Put up or Shet Up",
	"Keepin' It Illegal Concealment",
	"Ketamine n Rimjobs",
	"Kid Tested Mom Approved",
	"Kill Urself Boy",
	"Kill Urself Bro",
	"Kill Urself Dude",
	"KILL URSELF MAN",
	"Kill Urself Man",
	"Kill Urself My Man",
	"Kill Urself Nigga",
	"Kill Urself U Fool",
	"Kill Viper",
	"Killa of Legends",
	"Kingpin",
	"Last Revolution",
	"Laughin' at These Rappers Piece and Chain Compared to Mine",
	"Laughin' at These Rappers Piece and Chain Compared to Mine",
	"Learn from Me",
	"Leasure Tyme",
	"Leelicious",
	"Legend Killa",
	"LEGEND OF RAPCORE",
	"Let Her Dance 4 U",
	"Let's Do Tha Damn Thang",
	"Let's Get It in",
	"Let's Go Upstairs",
	"Let's Gone Get It In",
	"Let's Kill Viper",
	"Letal Dosage EP",
	"Lets Go Swimming",
	"Life Ain't Fair 4 U",
	"Life Ain't Fair 4 You'll",
	"Life Is Fair 4 Me",
	"Life Is Fair",
	"Life Is Fun 4 Me",
	"Life Is Fun",
	"Life Is Good",
	"Life Is so Fun",
	"Liquid Fury II",
	"Little Women",
	"Look Towards the Horizon Your Death Awaits You There.",
	"Loose Cannon!",
	"Loose Cannon",
	"Loved by All, Hated by None",
	"Luv at First Sight",
	"Luv Her Like U Do",
	"Luxury",
	"Made of Money",
	"Mafia God",
	"Mafia Hitman",
	"Make It Work",
	"Man of My Word",
	"Mild Mannered Mayhem",
	"Mo Than They No II",
	"Mo Than They No",
	"Mo Than U No II",
	"Mo Than U No",
	"Money 2 Burn, No Need 2 Earn",
	"Money Is Evrythang",
	"Money, Meth & Murda!",
	"Most Prized Possession",
	"Murda Broka II",
	"Murda Broka",
	"Murda Hustla Vol. II",
	"Murda II",
	"Murda Thug",
	"Murda, Vol. 2",
	"Murda",
	"Murder Me",
	"Murder Viper",
	"Muscles",
	"My Addiction",
	"My Collection of Guns",
	"My Eulogy",
	"My Fight 4 Control II",
	"My Gangland",
	"My Ghost Army",
	"My Liquid Fury, Vol. 2",
	"My Most Prized Possession",
	"My Piano Cake 3",
	"My Piano Cake",
	"My Prize Possession",
	"My Prized Possession",
	"My Riches Untamed",
	"My Soul Be Sold 2 Tha Devil Vol. II",
	"My Soul Be Sold 2 Tha Devil",
	"My Soul Is Sold 2 Tha Devil II",
	"My Soul Sold 2 Satan",
	"My Soul Sold 2 Tha Devil II",
	"Naturally II",
	"Naturally Real II",
	"Naturally Real",
	"Needs Ur Tenderness",
	"Neva a Foul-Calla",
	"Neva Callin' a Foul",
	"Neva Callin' Fouls",
	"Neva Eva a Foul-Calla",
	"No Foul-Calla",
	"No Fruntin Pure Stuntin",
	"No Fruntin' Just Stuntin'",
	"No Hesitation II",
	"No Hesitation",
	"No Marks in Space",
	"No My Rules!",
	"No My Rules",
	"No One Prettier",
	"No Tha Rules",
	"Non-Stop Bad B*tches Choosin' Me",
	"Non-Stop Bad B*tches Choosin'",
	"Not a Foul-Calla",
	"On Point",
	"On Tha Beaten Path",
	"Ot Wit Tha Old, in Wit Tha New",
	"Ot Wit' Tha Old in Wit' Tha New",
	"Paper Man",
	"Paper Man",
	"Paper Man",
	"Penitentiary Years Wit My Peers",
	"Phat Ass Aimin' Ur Way",
	"Piece of Mind",
	"Piece of Mine",
	"Pill Poppa 3",
	"Pill Poppa",
	"PIONEER OF RAPCORE",
	"Pistol Play",
	"Play Maker",
	"Pledge 2 Viper!",
	"Pledge 2 Viper",
	"Plush Player",
	"Plush Player",
	"Plush Player",
	"Plush Player",
	"Plush Player",
	"Plush Player",
	"Plush Player",
	"Points in Tha Paint",
	"Poppin' My Shirt off Everyday",
	"Prayin' 2 Throw Acid on a Cop's Face",
	"Pretty Boy Muscles",
	"Pretty",
	"Preyin 2 Throw Acid on a Cop's Face",
	"Pure Ability",
	"Pure Evil II",
	"Pure Evil",
	"Pure Genius",
	"Pure Stuntin'",
	"Purely Evil II",
	"Purely Evil",
	"Put Sum Relish and Musta on It It Ain't Extra 2",
	"Put That on Somethin'",
	"Put Up or Shet Up",
	"R U Tryna Fuck?",
	"R.I.P.",
	"Rap Cash",
	"Rap Game Money 2 Wild",
	"Rap Game Money Is Different",
	"Rap Game Money Is Much Different",
	"Rap Game Money Is so Wild",
	"Rap Game Money Is Wild",
	"Rap Made Me into a Man",
	"Rap Made Me into Tha Man",
	"Rap Money",
	"Rap Paid Me into a Man",
	"Rap Paid Me Into Tha Man",
	"Rapcore",
	"Ready and Willing Futuristic Space Age Remix Album",
	"Ready and Willing Futuristic Space Age Remix Album / Screwed and Chopped ",
	"Ready And Willing",
	"Ready And Willing",
	"Ready And Willing",
	"Ready and Willing",
	"Ready And Willing",
	"Ready And Willing",
	"Real Estate Checks",
	"REAL ESTATE MONEY",
	"Real Nigg@s Only Dunk 2-Hand Hanga",
	"Real Rapcore",
	"Real Talk",
	"Realest",
	"Recipe 4 Success",
	"Relax When U Come Home Baby",
	"Relax When U Come Home Baby",
	"Rememba Me?",
	"Resolve Unmatched",
	"Respect the Peace (Piece)",
	"Rest in Peace",
	"Rich and Not Famous",
	"Rich And NOT Famous",
	"Risen From Tha Ashes II",
	"Roll Call!",
	"Rotten 2 Tha Core II",
	"Rotten 2 Tha Core",
	"ROTTEN PAST MY CORE",
	"Rotten Thru Tha Core II",
	"Rotten Thru Tha Core",
	"Say Hi 2 Tha Twins",
	"Scenic Route II",
	"Scopin' These Nothin' F!Cks II",
	"Scopin' These Nothin' F@cks II",
	"See Through F*ck Into",
	"Sellin Dis Dope II",
	"Sellin' Dis Dope",
	"Sexies 4 U",
	"Sexy Dance 4 U",
	"Sexy Lady 4 U",
	"Shadow People",
	"Shadow People",
	"She Been Asking 4 U",
	"She Bought These 4 U",
	"She Eyeballin U My Man",
	"She Got a Kik",
	"She Lookin' for U",
	"She Luv U",
	"She Need Ur Lips",
	"She No U Got Powers",
	"She No U Want Tha Booty",
	"She Say She Want U",
	"She Still Suckin",
	"She Thinkin' of U",
	"She Told Me She Want U",
	"She Treat U Like a King",
	"She Twerk Hard for Ya Boi",
	"She Wanna Make Luv 2 U",
	"She Wanna Play",
	"She Wants U to Untie This",
	"She Wet 4 U",
	"She's Ready",
	"She's Strip Teasin' for U",
	"Shet Up Idiot",
	"Shet up U Stupid Idiot",
	"Shet Up",
	"Sick Stangin'",
	"Slide into Her Dms",
	"Slither EP",
	"Smarta Alternative",
	"Snitches Get Ditches",
	"Snorta of Cocaine",
	"So Much Cash I Got",
	"So Much Money I Keep",
	"So Pretty",
	"So Sick Stangin'",
	"Soul Sold 2 Satan",
	"Soul Sold 2 Tha Devil Vol .5",
	"Soul Sold 2 Tha Devil",
	"Soul Sold 2 That Devil Vol 3",
	"State of Art",
	"Still Sellin' Crack",
	"Still Slangin' Crack",
	"Str8 Stuntin' Stupid",
	"Str8 Stuntin'",
	"Str8 up Stuntin' on Boys",
	"Str8 up Stuntin' on Em'",
	"Str8 Up Stuntin' On U",
	"Str8 up Stuntin' Stupid",
	"Str8 Up Stuntin'",
	"Straight Up Stuntin'",
	"Strike Of The Viper",
	"Stuntin'",
	"Stuntin'",
	"Supa Crunk",
	"Swung a Hit Whea Tha Fuck I Seen It, Vol. 2",
	"T.R.A.P. Boy",
	"T.R.A.P. Boy",
	"T.R.A.P. Lord (Tall, Rich And Pretty)",
	"T.R.A.P. Lord (Tall, Rich and Pretty)",
	"Take a Pledge",
	"Take No Prisonas II",
	"Take No Prisonas",
	"Take Tha Pledge!",
	"Takin' No Prisonas",
	"Takin' No Prisoners II",
	"Tha Bad Apple",
	"Tha Best Creation of God",
	"Tha Code of Tha Streets",
	"Tha Cop Murdera",
	"Tha Crime Scenes",
	"Tha Deadly Weapon //",
	"Tha Deadly Weapon II",
	"Tha Deadly Weapon",
	"Tha Definition Of Gangsta",
	"Tha Dreams of a Rap Star",
	"Tha Evil 1 II",
	"Tha Evil 1",
	"Tha Fight 4 Control II",
	"Tha Genius",
	"Tha Gorgeous Boy",
	"Tha Greatest Thang Made by God",
	"Tha Greatest Thing Eva Made by God",
	"Tha Greatest Thing Made By God",
	"Tha Greatest Thing Our God's Ever Made",
	"Tha Hiram Clarke Hustla",
	"Tha Incomparable!",
	"Tha Incomparable",
	"Tha Journey as a Rich Man Begins",
	"Tha Journey Begins",
	"Tha Leada of Hardcore Rap",
	"Tha Lord of Rapcore",
	"Tha Originata Of Rapcore",
	"Tha Rap Cash",
	"Tha Realest 2 Eva Rap",
	"Tha Realest",
	"Tha Recipe 4 Success",
	"Tha Rocketship Bus 2",
	"Tha Scenic Route",
	"Tha Turf War",
	"Tha Worl C'mon Who Ben Round Ta See It Shit Don't Xist",
	"Thanksgivin'",
	"That Gorgeous Boy",
	`The 6' 2" Shorty`,
	"The Beast of the Best",
	"The Best to Ever Ball",
	"The G V",
	"The Gorgeous One",
	"The Greatest Creation of God",
	"The Greatest Creation of God",
	"The Grind Climb",
	"The Hiram Clarke Hustler Futuristic Space Age Remix Album",
	"The Hiram Clarke Hustler Futuristic Space Age Remix Album / Screwed and Chopped",
	"The Hiram Clarke Hustler",
	"The Leelicious",
	"The Music of Viper, Vol. 3",
	"The Oath of an Assassin",
	"The Paper Man Futuristic Space Age Remix Album / Screwed and Chopped",
	"The Paper Man",
	"The Prettiest Boy",
	"The Prettiest Prettyboy",
	"The Rise Of Viper",
	"The Southwest Hooligan Futuristic Space Age Remix Album / Screwed and Chopped",
	"The Southwest Hooligan",
	"The Threshold",
	"The Top-Choice Assassin",
	"There's a Recession?",
	"These Rappers Claim They Hard When Them Fags Never Even Seen The Pen",
	"These Rappers Claim They Hard When They Never Seen the Penitentiary",
	"These Rappers Claim They Hard",
	"They Know Me",
	"They Lookin 2 Clone Me",
	"They Lookin' 2 Copy Me",
	"They Lookin' Towards Clonin' Me",
	"They Lookin' Towards Copyin' Me",
	"They Pen Ain't Mightia Than My Pistol",
	"They Tryin' 2 Clone Me II",
	"They Tryin' 2 Clone Me",
	"They Wantin' 2 Clone Me",
	"They Wantin' 2 Copy Me II",
	"They Wantin' 2 Copy Me",
	"Thick Ass 4 U",
	"Things Thugs Do",
	"This Come Up",
	"Thug's Passion",
	"Thugs Of A Feather",
	"Tit 4 Tat",
	"Titties 4 U",
	"To Be or Not to Be",
	"Too Cute",
	"Too Pretty",
	"Tool",
	"Tools",
	"Top Goonin'",
	"Top Notch",
	"Top Winnin'",
	"Top-Notch II",
	"Top-Notch",
	"Trendsetter",
	"Triple Delite",
	"Try Ta Stop Me III",
	"Try ta Stop Me",
	"U a Means 2 an End",
	"U a Means to an End",
	"U A Snitch B*tch",
	"U a Snitch",
	"U a Stupid Dummy",
	"U a Stupid Idiot",
	"U Are a Dummy",
	"U Are an Idiot",
	"U Are an Idiot",
	"U Are an Imbecile",
	"U Are Below Me",
	"U Are Beneath Me",
	"U Are Dumb",
	"U Are Inferior 2 Me",
	"U Are Nothin'",
	"U Are Nothin'",
	"U Are so Dumb",
	"U Are so Stupid",
	"U Are so Trash",
	"U Are Such a Dummy",
	"U Are Such a Moron",
	"U Are Such an Idiot",
	"U Are Trash",
	"U Are Useless",
	"U Are Worthless",
	"U Broke Lil Nigga",
	"U BROKE",
	"U Can't Be That Stupid",
	"U Couldn't Be That Stupid",
	"U Coward F#cks!",
	"U Don't Know Me Little Nigger",
	"U Fallin' Off",
	"U Fallin' Off",
	"U Have No Value",
	"U Like It",
	"U Make Her Smile",
	"U on Her Mind",
	"U on Her Mind",
	"U Snitchin'?!",
	"U Ugly Big Nose Dude",
	"U Ugly Big Nose",
	"U Ugly Boy",
	"U Ugly Dude",
	"U Went to County Jail Not the Penitentiary Pussy Nigga",
	"U Wish Ur Gurl Was as Bad as Mine",
	"U'll Neva Amount 2 Nothin'",
	"U'll Never Amount to Me Boy",
	"U're a Moron",
	"U're so Dumb",
	"U're so Stupid",
	"U're So Stupid",
	"U're so Stupid",
	"U're Stupid",
	"U're Such a Dummy",
	"U're Such an Imbecile",
	"U's a Snitch",
	"Uppin' the Ante",
	"Ur Girl Dressed up Just for Me 1",
	"Ur in Her Dreams",
	"V the G",
	"Venom",
	"Viewa Discretion Is Advised",
	"Vigilance Always Pays Off II",
	"Vigilance Always Pays Off",
	"Vigilance Pays Off II",
	"Vigilance Pays Off",
	"Vipe Dogg",
	"Viper's Storytime",
	"Walkin' Dead Man",
	"Watchin' These Snitches",
	"What a Relief It Is",
	"What a Relief",
	"What I Live 4 II",
	"What Recession?",
	"What the F$Ck Is a Recession?",
	"What U Gone Do?",
	"What U Wanna Do?",
	"Where U @ Boo?",
	"Whip It Real Bad ;)",
	"Wicked Pistol Game",
	"Will U Ever Feel My Name?",
	"Will U Ever Know My Name?",
	"Winna Life!",
	"Winnin'",
	"Witot Hesitation",
	"Wrapped In Win",
	"Wrapped In Win",
	"Wrapped In Win",
	"Wrapped In Win",
	"Yo Baby Boo Handcuffin' Me",
	"Yo Baby Boo Holdin' Me",
	"Yo Baby Boo Luvin' Handcuffin' Me",
	"Yo Baby Mama Handcuffin' Me",
	"Yo Baby Mama Holdin' Me Down",
	"Yo Baby Mama Holdin' Me",
	"Yo Baby Mama Luvin' Handcuffin' Me",
	"Yo Baby Mama, Main & Side Holdin' Me II",
	"Yo Baby Mama, Main & Side Holdin' Me",
	"Yo Baby Mama, Side Thang & Main Thang Holdin' Me",
	"Yo Chic Chose Me",
	"Yo Chic Holdin' Me Down",
	"Yo Chic Holdin' Me",
	"Yo Cutie Pie Holdin' Me Down",
	"Yo Cutie Pie Keepin' Me in Her",
	"Yo Dame Holdin' Me Down",
	"Yo Girl Chose Me",
	"Yo Girl Handcuffin' Me",
	"Yo Girl Holdin' Me Down III",
	"Yo Girl Keepin' Me in Her",
	"Yo Girlfriend Handcuffin' Me",
	"Yo Girlfriend Holdin' Me Down",
	"Yo Girlfriend Luvin' Handcuffin' Me",
	"Yo Lady Holdin' Me Down",
	"Yo Main & Side Holdin' Me Down II",
	"Yo Main & Side Holdin' Me Down",
	"Yo Main & Side Thang Holdin' Me",
	"Yo Main Chic Holdin' Me Down",
	"Yo Main Dame Holdin' Me",
	"Yo Main Girl Holdin' Me",
	"Yo Main Girlfriend Holdin' Me",
	"Yo Main Handcuffin' Me",
	"Yo Main Holdin' Me Down",
	"Yo Main Lady Holdin' Me",
	"Yo Main Luvin' Handcuffin' Me",
	"Yo Main Thang & Side Thang Holdin' Me",
	"Yo Main Thang Handcuffin' Me",
	"Yo Main Thang Holdin' Me",
	"Yo Main Thang Luvin' Handcuffin' Me",
	"Yo Main Woman Holdin' Me Down",
	"Yo Old Lady Holdin' Me Down II",
	"Yo Old Lady Holdin' Me Down",
	"Yo Pretty Thang Holdin' Me Down",
	"Yo Pretty Thang Holdin' Me",
	"Yo Side & Main Holdin' Me II",
	"Yo Side & Main Holdin' Me",
	"Yo Side & Main Thang Holdin' Me Down",
	"Yo Side Thang & Main Thang Holdin' Me",
	"Yo Soulmate Holdin' Me Down II",
	"Yo Wife Chose Me",
	"Yo Wife F*cked Me & Fell in Luv",
	"Yo Wife Handcuffin' Me",
	"Yo Wife Holdin' Me",
	"Yo Wife Keepin' Me in Her",
	"Yo Wife Luvin' Handcuffin' Me",
	"Yo Woman Holdin' Me II",
	"Yo Woman Holdin' Me",
	"You'll Cowards Don't Even Smoke Crack Futuristic Space Age Remix Album",
	"You'll Cowards Don't Even Smoke Crack Futuristic Space Age Remix Album / Screwed and Chopped",
	"You'll Cowards Don't Even Smoke Crack 2",
	"You'll Cowards Don't Even Smoke Crack",
	"You'll Never Smoked Crack",
	"Your Fall Off",
];
export const SortedTitles = [
	"#EXPOSETHECOWARDS",
	"#viperrevolution",
	"1 Million Vipers but Only 1 Vipa",
	"1 Million Vipers but Only 1 Viper",
	"1,000,000 Vipers but Only 1 Vipa",
	"18 Wheela",
	"2 4 U",
	"2 Burn a Cop Alive",
	"2 Burn a Police Alive",
	"2 Decapitate a Cop",
	"2 Hot",
	"4eva Tha Realest",
	"A Day in the Life of Lee Carter",
	"A Greater Man",
	"A Greater Man Than U",
	"A Hustler's Life",
	"A Loose Cannon",
	"A Loyal Illuminati Memba",
	"A Loyal Illuminati Memba II",
	"A Sweet Eulogy",
	"A Young Hustler's Life (Baller's Mix)",
	"Ability",
	"Ability II",
	"Above All Law",
	"Above All Laws",
	"Addiction",
	"Ahead of All Tyme",
	"Ahead of His Tyme",
	"Ahead of U All Tha Tyme",
	"Ahead of Ur Tyme",
	"All 4 U Fam",
	"All Dis Money Dirty",
	"All Dogs Go to Heaven",
	"All Play No Work",
	"All Play, No Work",
	"All the Bad B*tches Choosin' Me",
	"Alot of Folk Countin' on Me",
	"Always Feelin Good",
	"An Unmatched Resolve",
	"Annihilation",
	"Aquatic Hoes",
	"Are U Really That Stupid",
	"Ass Floss",
	"At Peace Wit My Peace",
	"Atomic Bombs and Mutually Assured Destruction Is Fuckin' Stupid II",
	"Attackin' Tha Rim",
	"Attackin' Tha Rim Daily",
	"Bad Apple II",
	"Bad B*tches All On Me",
	"Bad B*tches Non-Stop Choosin' Me",
	"Bad B*tches Stayin' on Me",
	"Banned from Tha Rap Game",
	"Beach Hottie U Want",
	"Bearin' Interest",
	"Big Girls 4 U",
	"Bikini so Lovely",
	"Blessed by My Patience",
	"Blonde in Ur Bed",
	"Blood in, Blood Out",
	"Body Is a Temple",
	"Boo 4 U",
	"Booty 4 Days",
	"Boys Talkin' Down",
	"Break Bread",
	"Break Bread Bro",
	"Breakin' Tha Ice II",
	"Breakin' That Ice",
	"Business Cash",
	"Business Money",
	"Calculated Presence",
	"Cash Graze",
	"Celebrate",
	"Celebrate!",
	"Celebration",
	"Chin Checka",
	"Chopped And Screwed-Hustlin' Thick",
	"Cloned & Copied",
	"Cloned While Copied",
	"Cloudy Grinna",
	"Cocaine Snorta",
	"Code of Tha Streets",
	"Code of Tha Streets II",
	"Code of These Streets II",
	"Combo Breaker",
	"Concrete Jungle",
	"Confidence",
	"Confident II",
	"Cop Killa",
	"Cop Murdera",
	"Copied & Cloned",
	"Cops Can't Read",
	"Cops Can't Read III",
	"Crack Deala",
	"Crack Sella",
	"Creata of Hardcore Rap",
	"Creata of Rapcore",
	"Crime Scene",
	"Crime Scenes II",
	"Crunk",
	"Cum Here Now!!",
	"Damn I Want U Bad",
	"Dead Man Walkin'",
	"Deadly Weapon II",
	"Deala of Dope",
	"Deala of Dope 2",
	"Death Awaits",
	"Death Before Dishonor",
	"Death of a Salesman",
	"Deep in Tha Hustle",
	"Deep in That Hustle",
	"Defiance",
	"Defiant",
	"Dimples",
	"Dimples and Muscles",
	"Dis 4 Real",
	"Dis Deadly Weapon",
	"Dis Deadly Weapon II",
	"Dis Fight 4 Control",
	"Dis Fight 4 Control II",
	"Dis Liquid Fury",
	"Dis Liquid Fury II",
	"Dis Nigga Here!",
	"Dis What It Be 'Bout II",
	"Dis What It's All Bout",
	"Dis Winna Life!",
	"Do It in Tha Pool",
	"Don't Fuq Wit Her Clique",
	"Don't Knock My Hustle",
	"Don't Knock My Hustle!",
	"Don't Knock a Hustle",
	"Don't Talk Down",
	"Dope Deala",
	"Dream Steppin",
	"Dreams In The Penitentary",
	"Dreams of a Rap Star",
	"Educatin' Tha Community",
	"Education 4 Tha Community",
	"End Ur Life Dummy",
	"End Ur Life Stupid",
	"Engineered 2 Amaze II",
	"Engineered 2 Amaze U",
	"Eternal Parlayin'",
	"Eternal Playboy",
	"Eternal Prettyboy",
	"Euthanasia",
	"Euthanization",
	"Every Dog Has His Day",
	"Everyday a Vacation",
	"Evil 1",
	"Evil 1 II",
	"Evrythang I Live 4",
	"F!Ck U",
	"F!Ck U Pussy",
	"F!ck U Pussy-Ass N!gga",
	"F#ck U Bastards",
	"F#ck U Pussies",
	"F%Ck U Pussy-Ass N%Gga III",
	"F%ck U Pussy-Ass N%gga",
	"F%ck U Pussy-Ass N%gga II",
	"F%ck Ur Label Pussy",
	"F%ck Ur Record Label Pussy",
	"F%ck Ur Wedding",
	"F%ck a Wedding",
	"F%ck the Police!",
	"F%ck the Pussy Police!",
	"F*ck U",
	"F*ck What U Heard",
	"F*ck What U Sayin'",
	"F*ck the Pussy Police",
	"F@ck What U Believe In",
	"F@ck What U Goin' Through",
	"F@ck What U Stand 4",
	"F@ck the Police",
	"Find Me on Tha Beaten Path",
	"Fish And Chips",
	"Fish and Chips",
	"Folk Countin' on Me",
	"Forestry Maj-A Imma Keep Ur Lil Bears Safe",
	"Fuck Tha World It Ain't Real I Bend Tha Spoon Wit My Mind 2",
	"Fuck U Cops!!!",
	"Fuck U Cops!!! II",
	"Fuck U Little Nigger",
	"Fuck U Pussy-Ass Nigga",
	"Genius",
	"Get Loose Wit It",
	"Give It 2 Her",
	"Gleam",
	"God",
	"God Bless Rap F!Ck Hip Hop",
	"God Bless Rap F$ck Hip Hop",
	"God Bless Rap F%ck Hip Hop",
	"God Bless Rap F@ck Hip Hop",
	"God Has No Luv 4 U",
	"God Has No Respect 4 U",
	"God Hates U and Luvs Me",
	"God of Hardcore Rap",
	"God of Rapcore",
	"God's Favorite Human",
	"God's Favorite Human Being",
	"God's Greatest Creation",
	"Gorgeous",
	"Gorgeous Boy",
	"Got Tha Models Wide Open",
	"Gots 2 Make It Work",
	"Gots That Top Street Cred",
	"Gots a Wicked Pistol Game",
	"Grind Climb",
	"Grind To Shine",
	"H-Town's Top Choice",
	"Half Ur 6 Pac Higha Than Tha Otha Half",
	"Hard Work",
	"Haterproof",
	"Haters Talkin' Down",
	"Heartless Hoodlum",
	"Heartless Hoodlum (Viper-15 songs)",
	"Heartless Hoodlum Futuristic Space Age Remix Album (RymeTymerecords.com",
	"Heartless Hoodlum Futuristic Space Age Remix Album / Screwed and Chopped",
	"Heaven Is fo' Reel Muthafucka 3",
	"Hi Potency",
	"Hiram Clark Hustler",
	"Hiram Clarke Hustler",
	"Hoes Want to See U",
	"Hold Her Hand",
	"Hold U Down 4 Life",
	"Hole in Tha Sky Is Mad Real II",
	"Holy Mutha A' God",
	"Holy Mutha A' God II",
	"Hot Thang 4 U",
	"How Can I Help U?",
	"How I Make U Feel",
	"How It Makes U Feel II",
	"Human Cryonics: My Burial Site",
	"Human Cryostasis Gangsters Don't Die",
	"Hustlin Thick, Lovin Big",
	"Hustlin' Thick",
	"Hustlin' Thick Chopped and Screwed",
	"Hustlin' Thick II",
	"I Ain't Playin",
	"I Ain't Playin 3",
	"I Am Betta Than U",
	"I Am God",
	"I Am Superior",
	"I Am Superior 2 U",
	"I Am a Lot Smarter Than U",
	"I Be Real as Gold 4 Sho II",
	"I Found Ot I'm That Nigga",
	"I Got Tha Cure 4 a Broken Heart Right Here",
	"I Got Ya",
	"I Have Tha Best Piece & Chain Eva Made!",
	"I Have the Best Piece and Chain Ever Made",
	"I Know U Want It",
	"I Mastaed Life",
	"I No What U Been Missin'",
	"I Remember All My Dreams",
	"I Remember All My Dreams II",
	"I Seen a Skull",
	"I Sell Tha Best Crack",
	"I Sell Tha Best Crack 2",
	"I Win Always, U Loose Always",
	"I'm 5-9 Piru Blood (Now You Know My Set)",
	"I'm Alot Smarter Than U",
	"I'm Better Than U",
	"I'm Better Than U II",
	"I'm Gonna Kill Them Pussy Niggas That Killed 2Pac",
	"I'm Gonna Kill Them Pussy Niggas That Killed 2pac",
	"I'm Gonna Smoke Them Pussy Niggas That Killed 2Pac",
	"I'm Gonna Smoke Them Pussy Niggas That Killed 2pac",
	"I'm Gonna Smoke Them Pussy Niggas That Killed 2pac II",
	"I'm Greater Than U",
	"I'm Incredible",
	"I'm Lovin' Here Dis Rap Game Money",
	"I'm Luvin' Dis Here Rap Game",
	"I'm Luvin' Dis Here Rap Game II",
	"I'm Luvin' Dis Here Rap Game III",
	"I'm Luvin' Dis Here Rap Game...",
	"I'm Luvin' Dis Here Rap Money Cause It's Different",
	"I'm Luvin' Dis Here Rap Money Cause It's Different II",
	"I'm Luvin' Dis Rap Game",
	"I'm Luvin' Dis Rap Game Money",
	"I'm Luvin' Dis Rap Game Money II",
	"I'm Luvin' Dis Rap Game Money III",
	"I'm Luvin' Dis Rap Money Cause It's Different",
	"I'm Luvin' Dis Rap Money Cause It's Different Than Regular Money",
	"I'm Luvin' Tha Rap Money Cause It's Different",
	"I'm Much Smarter Than U",
	"I'm So Much Smarter Than U",
	"I'm a 5-9 Piru Blood",
	"I'm a Greater 1",
	"I'm a Greater 1 Than U",
	"I'm a Greater 1 Than U II",
	"I'm so Incredible",
	"I'm so Much Smarter Than U",
	"Ice Cold",
	"Im Better Than U",
	"Im Talkin' 'Bout Makin' the Bed Rock Like a Flintstone",
	"Impeccable",
	"Impeccable II",
	"In A Thug's Life",
	"In My Gat I Trust",
	"In Tha Life of a Rap Star",
	"Incomparable",
	"Incomparable!",
	"Interest Bearin'",
	"Inventa of Hardcore Rap",
	"It Don't Get No Betta",
	"It Would Be Heaven on Earth If Cops Were Drafted & Not Hired",
	"It'd Be Heaven On Earth If Cops Were Drafted & Not Hired",
	"It'd Be Heaven on Earth If Cops Were Drafted and Not Hired",
	"It's 4 Real",
	"It's All Because of Me ;-(",
	"It's All Because of U ;-(",
	"It's Because of Me",
	"It's Because of U ;-(",
	"It's Not Worth Yo Life",
	"It's Ok, U Can Judge Me",
	"It's Real",
	"Jagua Man 2",
	"Judged By 12, Saluted By a Million",
	"Just Put up or Shet Up",
	"KILL URSELF MAN",
	"Keepin' It Illegal Concealment",
	"Ketamine n Rimjobs",
	"Kid Tested Mom Approved",
	"Kill Urself Boy",
	"Kill Urself Bro",
	"Kill Urself Dude",
	"Kill Urself Man",
	"Kill Urself My Man",
	"Kill Urself Nigga",
	"Kill Urself U Fool",
	"Kill Viper",
	"Killa of Legends",
	"Kingpin",
	"LEGEND OF RAPCORE",
	"Last Revolution",
	"Laughin' at These Rappers Piece and Chain Compared to Mine",
	"Learn from Me",
	"Leasure Tyme",
	"Leelicious",
	"Legend Killa",
	"Let Her Dance 4 U",
	"Let's Do Tha Damn Thang",
	"Let's Get It in",
	"Let's Go Upstairs",
	"Let's Gone Get It In",
	"Let's Kill Viper",
	"Letal Dosage EP",
	"Lets Go Swimming",
	"Life Ain't Fair 4 U",
	"Life Ain't Fair 4 You'll",
	"Life Is Fair",
	"Life Is Fair 4 Me",
	"Life Is Fun",
	"Life Is Fun 4 Me",
	"Life Is Good",
	"Life Is so Fun",
	"Liquid Fury II",
	"Little Women",
	"Look Towards the Horizon Your Death Awaits You There.",
	"Loose Cannon",
	"Loose Cannon!",
	"Loved by All, Hated by None",
	"Luv Her Like U Do",
	"Luv at First Sight",
	"Luxury",
	"Made of Money",
	"Mafia God",
	"Mafia Hitman",
	"Make It Work",
	"Man of My Word",
	"Mild Mannered Mayhem",
	"Mo Than They No",
	"Mo Than They No II",
	"Mo Than U No",
	"Mo Than U No II",
	"Money 2 Burn, No Need 2 Earn",
	"Money Is Evrythang",
	"Money, Meth & Murda!",
	"Most Prized Possession",
	"Murda",
	"Murda Broka",
	"Murda Broka II",
	"Murda Hustla Vol. II",
	"Murda II",
	"Murda Thug",
	"Murda, Vol. 2",
	"Murder Me",
	"Murder Viper",
	"Muscles",
	"My Addiction",
	"My Collection of Guns",
	"My Eulogy",
	"My Fight 4 Control II",
	"My Gangland",
	"My Ghost Army",
	"My Liquid Fury, Vol. 2",
	"My Most Prized Possession",
	"My Piano Cake",
	"My Piano Cake 3",
	"My Prize Possession",
	"My Prized Possession",
	"My Riches Untamed",
	"My Soul Be Sold 2 Tha Devil",
	"My Soul Be Sold 2 Tha Devil Vol. II",
	"My Soul Is Sold 2 Tha Devil II",
	"My Soul Sold 2 Satan",
	"My Soul Sold 2 Tha Devil II",
	"Naturally II",
	"Naturally Real",
	"Naturally Real II",
	"Needs Ur Tenderness",
	"Neva Callin' Fouls",
	"Neva Callin' a Foul",
	"Neva Eva a Foul-Calla",
	"Neva a Foul-Calla",
	"No Foul-Calla",
	"No Fruntin Pure Stuntin",
	"No Fruntin' Just Stuntin'",
	"No Hesitation",
	"No Hesitation II",
	"No Marks in Space",
	"No My Rules",
	"No My Rules!",
	"No One Prettier",
	"No Tha Rules",
	"Non-Stop Bad B*tches Choosin'",
	"Non-Stop Bad B*tches Choosin' Me",
	"Not a Foul-Calla",
	"On Point",
	"On Tha Beaten Path",
	"Ot Wit Tha Old, in Wit Tha New",
	"Ot Wit' Tha Old in Wit' Tha New",
	"PIONEER OF RAPCORE",
	"Paper Man",
	"Penitentiary Years Wit My Peers",
	"Phat Ass Aimin' Ur Way",
	"Piece of Mind",
	"Piece of Mine",
	"Pill Poppa",
	"Pill Poppa 3",
	"Pistol Play",
	"Play Maker",
	"Pledge 2 Viper",
	"Pledge 2 Viper!",
	"Plush Player",
	"Points in Tha Paint",
	"Poppin' My Shirt off Everyday",
	"Prayin' 2 Throw Acid on a Cop's Face",
	"Pretty",
	"Pretty Boy Muscles",
	"Preyin 2 Throw Acid on a Cop's Face",
	"Pure Ability",
	"Pure Evil",
	"Pure Evil II",
	"Pure Genius",
	"Pure Stuntin'",
	"Purely Evil",
	"Purely Evil II",
	"Put Sum Relish and Musta on It It Ain't Extra 2",
	"Put That on Somethin'",
	"Put Up or Shet Up",
	"R U Tryna Fuck?",
	"R.I.P.",
	"REAL ESTATE MONEY",
	"ROTTEN PAST MY CORE",
	"Rap Cash",
	"Rap Game Money 2 Wild",
	"Rap Game Money Is Different",
	"Rap Game Money Is Much Different",
	"Rap Game Money Is Wild",
	"Rap Game Money Is so Wild",
	"Rap Made Me into Tha Man",
	"Rap Made Me into a Man",
	"Rap Money",
	"Rap Paid Me Into Tha Man",
	"Rap Paid Me into a Man",
	"Rapcore",
	"Ready And Willing",
	"Ready and Willing Futuristic Space Age Remix Album",
	"Ready and Willing Futuristic Space Age Remix Album / Screwed and Chopped",
	"Real Estate Checks",
	"Real Nigg@s Only Dunk 2-Hand Hanga",
	"Real Rapcore",
	"Real Talk",
	"Realest",
	"Recipe 4 Success",
	"Relax When U Come Home Baby",
	"Rememba Me?",
	"Resolve Unmatched",
	"Respect the Peace (Piece)",
	"Rest in Peace",
	"Rich And NOT Famous",
	"Rich and Not Famous",
	"Risen From Tha Ashes II",
	"Roll Call!",
	"Rotten 2 Tha Core",
	"Rotten 2 Tha Core II",
	"Rotten Thru Tha Core",
	"Rotten Thru Tha Core II",
	"Say Hi 2 Tha Twins",
	"Scenic Route II",
	"Scopin' These Nothin' F!Cks II",
	"Scopin' These Nothin' F@cks II",
	"See Through F*ck Into",
	"Sellin Dis Dope II",
	"Sellin' Dis Dope",
	"Sexies 4 U",
	"Sexy Dance 4 U",
	"Sexy Lady 4 U",
	"Shadow People",
	"She Been Asking 4 U",
	"She Bought These 4 U",
	"She Eyeballin U My Man",
	"She Got a Kik",
	"She Lookin' for U",
	"She Luv U",
	"She Need Ur Lips",
	"She No U Got Powers",
	"She No U Want Tha Booty",
	"She Say She Want U",
	"She Still Suckin",
	"She Thinkin' of U",
	"She Told Me She Want U",
	"She Treat U Like a King",
	"She Twerk Hard for Ya Boi",
	"She Wanna Make Luv 2 U",
	"She Wanna Play",
	"She Wants U to Untie This",
	"She Wet 4 U",
	"She's Ready",
	"She's Strip Teasin' for U",
	"Shet Up",
	"Shet Up Idiot",
	"Shet up U Stupid Idiot",
	"Sick Stangin'",
	"Slide into Her Dms",
	"Slither EP",
	"Smarta Alternative",
	"Snitches Get Ditches",
	"Snorta of Cocaine",
	"So Much Cash I Got",
	"So Much Money I Keep",
	"So Pretty",
	"So Sick Stangin'",
	"Soul Sold 2 Satan",
	"Soul Sold 2 Tha Devil",
	"Soul Sold 2 Tha Devil Vol .5",
	"Soul Sold 2 That Devil Vol 3",
	"State of Art",
	"Still Sellin' Crack",
	"Still Slangin' Crack",
	"Str8 Stuntin'",
	"Str8 Stuntin' Stupid",
	"Str8 Up Stuntin'",
	"Str8 Up Stuntin' On U",
	"Str8 up Stuntin' Stupid",
	"Str8 up Stuntin' on Boys",
	"Str8 up Stuntin' on Em'",
	"Straight Up Stuntin'",
	"Strike Of The Viper",
	"Stuntin'",
	"Supa Crunk",
	"Swung a Hit Whea Tha Fuck I Seen It, Vol. 2",
	"T.R.A.P. Boy",
	"T.R.A.P. Lord (Tall, Rich And Pretty)",
	"Take No Prisonas",
	"Take No Prisonas II",
	"Take Tha Pledge!",
	"Take a Pledge",
	"Takin' No Prisonas",
	"Takin' No Prisoners II",
	"Tha Bad Apple",
	"Tha Best Creation of God",
	"Tha Code of Tha Streets",
	"Tha Cop Murdera",
	"Tha Crime Scenes",
	"Tha Deadly Weapon",
	"Tha Deadly Weapon //",
	"Tha Deadly Weapon II",
	"Tha Definition Of Gangsta",
	"Tha Dreams of a Rap Star",
	"Tha Evil 1",
	"Tha Evil 1 II",
	"Tha Fight 4 Control II",
	"Tha Genius",
	"Tha Gorgeous Boy",
	"Tha Greatest Thang Made by God",
	"Tha Greatest Thing Eva Made by God",
	"Tha Greatest Thing Made By God",
	"Tha Greatest Thing Our God's Ever Made",
	"Tha Hiram Clarke Hustla",
	"Tha Incomparable",
	"Tha Incomparable!",
	"Tha Journey Begins",
	"Tha Journey as a Rich Man Begins",
	"Tha Leada of Hardcore Rap",
	"Tha Lord of Rapcore",
	"Tha Originata Of Rapcore",
	"Tha Rap Cash",
	"Tha Realest",
	"Tha Realest 2 Eva Rap",
	"Tha Recipe 4 Success",
	"Tha Rocketship Bus 2",
	"Tha Scenic Route",
	"Tha Turf War",
	"Tha Worl C'mon Who Ben Round Ta See It Shit Don't Xist",
	"Thanksgivin'",
	"That Gorgeous Boy",
	"The Best to Ever Ball",
	"The G V",
	"The Gorgeous One",
	"The Greatest Creation of God",
	"The Grind Climb",
	"The Hiram Clarke Hustler",
	"The Hiram Clarke Hustler Futuristic Space Age Remix Album",
	"The Hiram Clarke Hustler Futuristic Space Age Remix Album / Screwed and Chopped",
	"The Leelicious",
	"The Music of Viper, Vol. 3",
	"The Oath of an Assassin",
	"The Paper Man",
	"The Paper Man Futuristic Space Age Remix Album / Screwed and Chopped",
	"The Prettiest Boy",
	"The Prettiest Prettyboy",
	"The Rise Of Viper",
	"The Southwest Hooligan",
	"The Southwest Hooligan Futuristic Space Age Remix Album / Screwed and Chopped",
	"The Threshold",
	"The Top-Choice Assassin",
	"There's a Recession?",
	"These Rappers Claim They Hard",
	"These Rappers Claim They Hard When Them Fags Never Even Seen The Pen",
	"These Rappers Claim They Hard When They Never Seen the Penitentiary",
	"They Know Me",
	"They Lookin 2 Clone Me",
	"They Lookin' 2 Copy Me",
	"They Lookin' Towards Clonin' Me",
	"They Lookin' Towards Copyin' Me",
	"They Pen Ain't Mightia Than My Pistol",
	"They Tryin' 2 Clone Me",
	"They Tryin' 2 Clone Me II",
	"They Wantin' 2 Clone Me",
	"They Wantin' 2 Copy Me",
	"They Wantin' 2 Copy Me II",
	"Thick Ass 4 U",
	"Things Thugs Do",
	"This Come Up",
	"Thug's Passion",
	"Thugs Of A Feather",
	"Tit 4 Tat",
	"Titties 4 U",
	"To Be or Not to Be",
	"Too Cute",
	"Too Pretty",
	"Tool",
	"Tools",
	"Top Goonin'",
	"Top Notch",
	"Top Winnin'",
	"Top-Notch",
	"Top-Notch II",
	"Trendsetter",
	"Triple Delite",
	"Try Ta Stop Me III",
	"Try ta Stop Me",
	"U A Snitch B*tch",
	"U Are Below Me",
	"U Are Beneath Me",
	"U Are Dumb",
	"U Are Inferior 2 Me",
	"U Are Nothin'",
	"U Are Such a Dummy",
	"U Are Such a Moron",
	"U Are Such an Idiot",
	"U Are Trash",
	"U Are Useless",
	"U Are Worthless",
	"U Are a Dummy",
	"U Are an Idiot",
	"U Are an Imbecile",
	"U Are so Dumb",
	"U Are so Stupid",
	"U Are so Trash",
	"U BROKE",
	"U Broke Lil Nigga",
	"U Can't Be That Stupid",
	"U Couldn't Be That Stupid",
	"U Coward F#cks!",
	"U Don't Know Me Little Nigger",
	"U Fallin' Off",
	"U Have No Value",
	"U Like It",
	"U Make Her Smile",
	"U Snitchin'?!",
	"U Ugly Big Nose",
	"U Ugly Big Nose Dude",
	"U Ugly Boy",
	"U Ugly Dude",
	"U Went to County Jail Not the Penitentiary Pussy Nigga",
	"U Wish Ur Gurl Was as Bad as Mine",
	"U a Means 2 an End",
	"U a Means to an End",
	"U a Snitch",
	"U a Stupid Dummy",
	"U a Stupid Idiot",
	"U on Her Mind",
	"U'll Neva Amount 2 Nothin'",
	"U'll Never Amount to Me Boy",
	"U're So Stupid",
	"U're Stupid",
	"U're Such a Dummy",
	"U're Such an Imbecile",
	"U're a Moron",
	"U're so Dumb",
	"U're so Stupid",
	"U's a Snitch",
	"Uppin' the Ante",
	"Ur Girl Dressed up Just for Me 1",
	"Ur in Her Dreams",
	"V the G",
	"Venom",
	"Viewa Discretion Is Advised",
	"Vigilance Always Pays Off",
	"Vigilance Always Pays Off II",
	"Vigilance Pays Off",
	"Vigilance Pays Off II",
	"Vipe Dogg",
	"Viper's Storytime",
	"Walkin' Dead Man",
	"Watchin' These Snitches",
	"What I Live 4 II",
	"What Recession?",
	"What U Gone Do?",
	"What U Wanna Do?",
	"What a Relief",
	"What a Relief It Is",
	"What the F$Ck Is a Recession?",
	"Where U @ Boo?",
	"Whip It Real Bad ;)",
	"Wicked Pistol Game",
	"Will U Ever Feel My Name?",
	"Will U Ever Know My Name?",
	"Winna Life!",
	"Winnin'",
	"Witot Hesitation",
	"Wrapped In Win",
	"Yo Baby Boo Handcuffin' Me",
	"Yo Baby Boo Holdin' Me",
	"Yo Baby Boo Luvin' Handcuffin' Me",
	"Yo Baby Mama Handcuffin' Me",
	"Yo Baby Mama Holdin' Me",
	"Yo Baby Mama Holdin' Me Down",
	"Yo Baby Mama Luvin' Handcuffin' Me",
	"Yo Baby Mama, Main & Side Holdin' Me",
	"Yo Baby Mama, Main & Side Holdin' Me II",
	"Yo Baby Mama, Side Thang & Main Thang Holdin' Me",
	"Yo Chic Chose Me",
	"Yo Chic Holdin' Me",
	"Yo Chic Holdin' Me Down",
	"Yo Cutie Pie Holdin' Me Down",
	"Yo Cutie Pie Keepin' Me in Her",
	"Yo Dame Holdin' Me Down",
	"Yo Girl Chose Me",
	"Yo Girl Handcuffin' Me",
	"Yo Girl Holdin' Me Down III",
	"Yo Girl Keepin' Me in Her",
	"Yo Girlfriend Handcuffin' Me",
	"Yo Girlfriend Holdin' Me Down",
	"Yo Girlfriend Luvin' Handcuffin' Me",
	"Yo Lady Holdin' Me Down",
	"Yo Main & Side Holdin' Me Down",
	"Yo Main & Side Holdin' Me Down II",
	"Yo Main & Side Thang Holdin' Me",
	"Yo Main Chic Holdin' Me Down",
	"Yo Main Dame Holdin' Me",
	"Yo Main Girl Holdin' Me",
	"Yo Main Girlfriend Holdin' Me",
	"Yo Main Handcuffin' Me",
	"Yo Main Holdin' Me Down",
	"Yo Main Lady Holdin' Me",
	"Yo Main Luvin' Handcuffin' Me",
	"Yo Main Thang & Side Thang Holdin' Me",
	"Yo Main Thang Handcuffin' Me",
	"Yo Main Thang Holdin' Me",
	"Yo Main Thang Luvin' Handcuffin' Me",
	"Yo Main Woman Holdin' Me Down",
	"Yo Old Lady Holdin' Me Down",
	"Yo Old Lady Holdin' Me Down II",
	"Yo Pretty Thang Holdin' Me",
	"Yo Pretty Thang Holdin' Me Down",
	"Yo Side & Main Holdin' Me",
	"Yo Side & Main Holdin' Me II",
	"Yo Side & Main Thang Holdin' Me Down",
	"Yo Side Thang & Main Thang Holdin' Me",
	"Yo Soulmate Holdin' Me Down II",
	"Yo Wife Chose Me",
	"Yo Wife F*cked Me & Fell in Luv",
	"Yo Wife Handcuffin' Me",
	"Yo Wife Holdin' Me",
	"Yo Wife Keepin' Me in Her",
	"Yo Wife Luvin' Handcuffin' Me",
	"Yo Woman Holdin' Me",
	"Yo Woman Holdin' Me II",
	"You'll Cowards Don't Even Smoke Crack",
	"You'll Cowards Don't Even Smoke Crack 2",
	"You'll Cowards Don't Even Smoke Crack Futuristic Space Age Remix Album",
	"You'll Cowards Don't Even Smoke Crack Futuristic Space Age Remix Album / Screwed and Chopped",
	"You'll Never Smoked Crack",
	"Your Fall Off",
	'F$Ck 24" And Up',
	"F$ck All 24 and Up",
	'Google "Rapper Viper"',
	"Google Rapper Viper Now",
	`The 6' 2" Shorty`,
	"The Beast of the Best"
];
